In [2]:
import numpy as np

In [3]:
# Task-1


# n = int(input())
# arr = np.zeros(n, dtype=int)
# for i in range(n):
#     arr[i] = int(input())

# new_element = int(input())
# new_arr = np.append(arr, new_element)

# print("Original Array: ", arr)
# print("Resized Array: ", new_arr)

n=int(input())
arr=np.zeros(n,dtype=int)
for i in range(n):
    arr[i]= int(input())
new_arr=np.zeros(n+1,dtype=int)
for i in range(n+1):
    if(n>i):
        new_arr[i]=arr[i]
    else:
        new_arr[i]=int(input())
print("Orginal Array: ",arr)
print("Resized Array: ",new_arr)

Orginal Array:  [1 2 3]
Resized Array:  [1 2 3 4]


In [4]:
# Task-2

# n = int(input())
# arr = np.zeros(n, dtype=int)
# for i in range(n):
#     arr[i] = int(input())

# new_arr = np.where(arr > 0, 1, 0)

# print("Original Array: ", arr)
# print("After modifying: ", new_arr)

n=int(input())
arr=np.zeros(n,dtype=int)
for i in range(n):
    arr[i]= int(input())
new_arr=np.zeros(n,dtype=int)
for i in range(n):
    if(arr[i]>0):
        new_arr[i]=1
    else:
        new_arr[i]=0
print("Orginal Array: ",arr)
print("After modifying: ",new_arr)

Orginal Array:  [1 2 3]
After modifying:  [1 1 1]


In [ ]:
# Task-3
def reverseArray(arr1):
    for i in range(arr1.size//2+1):
        temp=arr1[i]
        arr1[i]=arr1[arr1.size-i-1]
        arr1[arr1.size-i-1]=temp
    return arr1
arr1 = np.array([10, 12, 20, 5, 7]) 
arr1 = reverseArray(arr1) 
print(arr1)




[ 7  5 20 12 10]


In [ ]:
# Task-4

# def printPairs(arr, target):
#     seen = set()
#     for num in arr:
#         diff = target - num
#         if diff in seen:
#             print(num, diff, sep=",")
#         seen.add(num)

# arr1 = np.array([7,8,10,5,3,4,2]) 
# printPairs(arr1, 15)

def printPairs(arr,target):
    flag=True
    for i in range(arr.size):
        for j in range(i+1,arr.size):
            if(arr[i]+arr[j]==target):
                flag=False
                print(arr[i],arr[j],sep=",")
    if(flag):
        print("No Pair Found")

arr2 = np.array([2,-3,1,9,4,5]) 
printPairs(arr2, 6)

2,4
-3,9
1,5


In [ ]:
# Task-5


# vec1 = np.array([1,2,3,7]) 
# vec2 = np.array([4,5,6,9])

# dot_product = np.dot(vec1, vec2)
# print("Dot Product: ", dot_product)

# if dot_product & 1:
#     vec1[1::2], vec2[1::2] = vec2[1::2], vec1[1::2].copy()
# else:
#     vec1[::2], vec2[::2] = vec2[::2], vec1[::2].copy()

# print("After swapping: ")
# print(vec1)
# print(vec2)

vec1 = np.array([1,2,3,7]) 
vec2 = np.array([4,5,6,9])

sum=0
for i in range(vec1.size):
    sum+=vec1[i]*vec2[i]
print("Dot Product:",sum)

if(sum&1):
    for i in range(vec1.size):
        if(i&1):
            temp=vec1[i]
            vec1[i]=vec2[i]
            vec2[i]=temp
else:
    for i in range(vec1.size):
        if(not i&1):
            temp=vec1[i]
            vec1[i]=vec2[i]
            vec2[i]=temp

print("After swapping: ")
print(vec1)
print(vec2)


Dot Product:  95
After swapping: 
[1 5 3 9]
[4 2 6 7]


In [ ]:
# Task-6

n=int(input())
arr=np.zeros(n,dtype=int)
for i in range(n):
    arr[i]= int(input())

print("Orginal Array: ",arr)
for i in range(n):
    min=i
    for j in range(i+1,n):
        if(arr[j]<arr[min]):
            min=j
    arr[i], arr[min] = arr[min], arr[i]
print("Sorted Array: ",arr)

Orginal Array:  [0 3 2]
Sorted Array:  [0 2 3]


In [ ]:
# Task-7

def flatten(arr):
    row=arr.shape[0]
    col=arr.shape[1]
    new_arr=np.zeros(row*col,dtype=int)
    for i in range(row):
        for j in range(col):
            new_arr[i*col+j]=arr[i][j]
    return new_arr
arr1 = np.array( [ [1, 2, 3], [3, 4, 5] ] )
arr2 = flatten(arr1) 
print(arr2)


[1 2 3 3 4 5]


In [ ]:
# Task-8


A = np.array([ [1, 0, 0], [0, 1, 0],
[0, 0, 1] ])
row=A.shape[0]
col=A.shape[1]

flag=True

for i in range(row):
    for j in range(col):
        if((i==j and A[i][j]!=1) or (i!=j and A[i][j]!=0)):
            print("Not a Identity Matrix")
            flag=False
            break
    if(not flag):
        break
if(flag):
    print("Identity Matrix")
            


Identity Matrix


In [ ]:
# Task-9

A = np.array([ [1, 5, 12, 1], [2, -4, 6, 7],
[3, 8, 5, 9],
[3, 5, 23, -6] ])

row=A.shape[0]
col=A.shape[1]

pd=0
sd=0

for i in range(row):
    for j in range(col):
        if(i==j):
            pd+=A[i][j]
        if(i+j==row-1):
            sd+=A[i][j]

print(abs(pd-sd))

22


In [ ]:
# Task-10
A = np.array([[1, 2, 3], [4, 5, 6],
[7, 8, 9]])

row=A.shape[0]
col=A.shape[1]
Transpose=np.zeros((col,row),dtype=int)
for i in range(col):
    for j in range(row):
        Transpose[i][j]=A[j][i]
print(Transpose)

gram=np.zeros((col,col),dtype=int)
for i in range(col):
    for j in range(col):
        for k in range(row):
            gram[i][j]+=Transpose[i][k]*A[k][j]

print(gram)


[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [1]:
# Task-11
import numpy as np
A = np.array([[4,1,2], [9,3,7]],dtype=float)
row=A.shape[0]
col=A.shape[1]

avg=0
for i in range(col):
    avg+=A[abs(row-col)%row][i]/col
avg=int(avg*100)/100
# for i in range(row):
#     for j in range(col):
#         A[i][j]*=avg
print(A*avg)


[[25.32  6.33 12.66]
 [56.97 18.99 44.31]]
